### ISSUE TITLE
dory自带环境的harbor安装会报错

### ISSUE THREAD

**Issue by vicnoah** [dory-engine/dory-ctl#2]
ls: cannot access '/var/lib/postgresql/data/pgdata': No such file or directory

 The files belonging to this database system will be owned by user "postgres".

 This user must also own the server process.

 

 initdb: error: could not create directory "/var/lib/postgresql/data/pgdata": Permission denied

 The database cluster will be initialized with locales

   COLLATE:  en_US.UTF-8

   CTYPE:    en_US.UTF-8

   MESSAGES: C

   MONETARY: C

   NUMERIC:  C

   TIME:     C

 The default text search configuration will be set to "english".

 

 Data page checksums are disabled.

 

 creating directory /var/lib/postgresql/data/pgdata/pg13 ...

**Comment by cookeem** [comment]
@vicnoah 如果你是用的是本地存储，那么就是你的rootDir和kubernetes.pvConfigLocal.localPath设置有误，我更新了相关的说明：

```yaml
  # # 假如持久化存储使用本地存储情况下请设置，否则请删除以下配置
  # pvConfigLocal:
  #   # 本地存储路径（绝对路径）
  #   # 注意，与前边的`rootDir`设置一致
  #   localPath: "/data/k8s-vols/dory-ce"

  # 假如持久化存储使用nfs情况下请设置，否则请删除以下配置
  pvConfigNfs:
    # nfs存储路径（绝对路径）
    # 注意，这里是nfs服务器上的nfs目录，对应前边的`rootDir`设置，非本机挂装目录
    nfsPath: "/data/nfs-vols/k8s-vols/dory-ce"
    # nfs服务器地址
    nfsServer: "10.2.0.10"

  # # 假如持久化存储使用cephfs情况下请设置，否则请删除以下配置
  # pvConfigCephfs:
  #   # ceph存储路径（绝对路径）
  #   # 注意，这里是cephfs服务器上的cephfs目录，对应前边的`rootDir`设置，非本机挂装目录
  #   cephPath: "/k8s-vols/dory-ce"
  #   # ceph账号
  #   cephUser: admin
  #   # ceph秘钥
  #   cephSecret: "xxx"
  #   # ceph monitor地址
  #   cephMonitors:
  #   - "192.168.0.1:6789"
  #   - "192.168.0.2:6789"
  #   - "192.168.0.3:6789"
```
