### ISSUE TITLE
安装后harbor存在问题

### ISSUE THREAD

**Issue by vicnoah** [dory-engine/dory-ctl#3]
![image](https://user-images.githubusercontent.com/20820831/157579536-ea07e591-06ba-4176-9046-d5666634567f.png)
报错信息，连不上harbor仓库
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://harbor.dory.local/v2/": dial tcp 192.168.0.31:443: connect: connection refused
[WARN] [03-10 10:47:18]: ####################################################
[WARN] [03-10 10:47:18]: PLEASE FOLLOW THE INSTRUCTION TO REMOVE DORY INSTALL
[WARN] [03-10 10:47:18]: README.md located at: readme-install-kubernetes/README-kubernetes-reset.md
[WARN] [03-10 10:47:18]: ####################################################
[WARN] [03-10 10:47:18]: 
# 清除kubernetes方式部署的服务

### 停止并清除 harbor 服务

```shell script
helm -n harbor uninstall harbor
```

### 停止并清除所有 dory 服务

```shell script
# cd to readme directory
kubectl delete namespace dory
kubectl delete namespace harbor
kubectl delete pv dory-pv
kubectl delete pv harbor-pv
kubectl delete pv project-data-pv
```

## 所有dory组件的数据存放位置

- 所有dory组件的数据存放在: `/mydata/dory/k8s-vols/dory-ce`

```shell script
# 重新安装前，请清理dory组件数据
rm -rf /mydata/dory/k8s-vols/dory-ce/*
```

[ERRO] [03-10 10:47:18]: install harbor error: exec docker login --username admin --password wcVouYdhnQEL8S05= harbor.dory.local error: exit status: 1
[ERRO] [03-10 10:47:18]: install harbor error: exec docker login --username admin --password wcVouYdhnQEL8S05= harbor.dory.local error: exit status: 1

**Comment by cookeem** [comment]
1. 检查一下你的/etc/hosts是否自动添加了harbor的地址解析。
2. 检查你的harbor是否已经正常启动，并且可以正常访问服务。
3. 检查你的登录密码是否正确，有一种可能是你没有清理harbor的数据库，导致登录密码用的是上一次随机生成的密码。

**Comment by vicnoah** [comment]
> 

打不开harbor,hosts是正常的。我再看看

**Comment by cookeem** [comment]
看看harbor的日志，检查一下doryctl install check相关的步骤有没有做。

**Comment by cookeem** [comment]
建议你可以使用doryctl install script来先手工走一遍流程，这个命令会自动生成所有配置文件，以及相关的安装说明详细步骤。你一步一步copy里边的命令执行，确实出现问题你就很容易找原因，避免自动安装有一步失败必须全部重新跑一遍的尴尬。

**Comment by vicnoah** [comment]
> 建议你可以使用doryctl install script来先手工走一遍流程，这个命令会自动生成所有配置文件，以及相关的安装说明详细步骤。你一步一步copy里边的命令执行，确实出现问题你就很容易找原因，避免自动安装有一步失败必须全部重新跑一遍的尴尬。

看到了，没做check。我没有traefik ingress。

**Comment by vicnoah** [comment]
> > 建议你可以使用doryctl install script来先手工走一遍流程，这个命令会自动生成所有配置文件，以及相关的安装说明详细步骤。你一步一步copy里边的命令执行，确实出现问题你就很容易找原因，避免自动安装有一步失败必须全部重新跑一遍的尴尬。
> 
> 看到了，没做check。我没有traefik ingress。

我以为check就是检查我又没有安装k8s，所以我就没做这个步骤

**Comment by vicnoah** [comment]
> 建议你可以使用doryctl install script来先手工走一遍流程，这个命令会自动生成所有配置文件，以及相关的安装说明详细步骤。你一步一步copy里边的命令执行，确实出现问题你就很容易找原因，避免自动安装有一步失败必须全部重新跑一遍的尴尬。

我重试过还是这个错误，也用check命令检查了。除了没有使用traefik ingress(我用的nginx ingress)

**Comment by cookeem** [comment]
nginx ingress我确实还有测试过，有可能是harbor官方部署文件里边需要针对nginx ingress做特殊设置。
harbor中的values.yaml里边的设置
```yaml
  ingress:
    hosts:
      core: {{ $.imageRepo.domainName }}
      notary: notary.{{ $.imageRepo.domainName }}
    # set to the type of ingress controller if it has specific requirements.
    # leave as `default` for most ingress controllers.
    # set to `gce` if using the GCE ingress controller
    # set to `ncp` if using the NCP (NSX-T Container Plugin) ingress controller
    controller: default
    annotations:
      # note different ingress controllers may require a different ssl-redirect annotation
      # for Envoy, use ingress.kubernetes.io/force-ssl-redirect: "true" and remove the nginx lines below
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"

```

应该是这段导致与nginx-ingress不兼容
